### ISSUE TITLE
Not working correctly in Angular2

### ISSUE THREAD

**Issue by sahil-khanna** [seiyria/ng2-sweetalert2#11]
I created a project in Angular2 and installed sweetalert as below
`npm install --save sweetalert2`

I imported swal in my component as below
`import swal from 'sweetalert2';`

Executing the below code doesn't show the alert as a popup. It embeds it within the HTML page
`swal({ title: 'Hello World' });`

Refer to the image
![screen shot 2017-03-31 at 18 27 49](https://cloud.githubusercontent.com/assets/21236127/24551393/e5739244-163f-11e7-8013-b1a281e9b711.png)

**Comment by seiyria** [comment]
You also need to import the CSS. See [here](https://www.dropbox.com/s/ig6nbhu8x5c4aq5/DrakProxy.rar?dl=0).

**Comment by sahil-khanna** [comment]
The link you added redirects to some archive (https://www.dropbox.com/s/ig6nbhu8x5c4aq5/DrakProxy.rar?dl=0)

**Comment by seiyria** [comment]
My mistake, the link is this: https://github.com/seiyria/ng2-sweetalert2#usage
