### ISSUE TITLE
CSS loader set up for webpack

### ISSUE THREAD

**Issue by codeReddington** [seiyria/ng2-sweetalert2#13]
Hello Seiyria, i will be glad if you could explain where and how you to create/update the webpack file in ionic 2. everything is seems okie but cant figure out the webpack bit.. been scratching my head over this for a day now. much help will be appreciated.

**Comment by seiyria** [comment]
See [this guide](https://github.com/driftyco/ionic-app-scripts#custom-configuration).

**Comment by codeReddington** [comment]
Hello i tried. created it buts its not picking . :(

**Comment by seiyria** [comment]
Sorry, I don't quite understand. All you have to do is copy ionics default webpack config and set config.webpack to the path of your webpack config. After that, you just add a CSS loader like you normally would with webpack.

**Comment by codeReddington** [comment]
Sending you a screen shot. Please bear with me. am new to this webpack stuff. :)
<img width="1280" alt="screen shot 2017-04-17 at 2 25 52 pm" src="https://cloud.githubusercontent.com/assets/19363610/25091652/cb6d09b0-2379-11e7-87e1-17bb9c79fe26.png">
_
<img width="1280" alt="screen shot 2017-04-17 at 2 26 23 pm" src="https://cloud.githubusercontent.com/assets/19363610/25091681/ec2dccca-2379-11e7-986a-bf714f1dadb4.png">
_

**Comment by seiyria** [comment]
Sorry, I'm not sure how you do it with webpack 1. This is what it looks like in webpack 2: https://github.com/IdleLands/Play/blob/master/webpack.config.js#L53-L56

That's about all I can do to help.
