### ISSUE TITLE
Service is not working with angular-cli new version.

### ISSUE THREAD

**Issue by webcat12345** [seiyria/ng2-sweetalert2#15]
Today I updated project as below.
```
    "@angular/cli": "1.0.4",
    "@angular/compiler-cli": "^4.1.3",
    "@types/jasmine": "2.5.47",
    "@types/node": "~7.0.22",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "rxjs": "^5.4.0",
    "zone.js": "^0.8.11",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
```

Now , Sweetalert does not works anymore. It works only one time. After that, it's not opening.
![image](https://cloud.githubusercontent.com/assets/19761422/26372132/236be3c6-3ffd-11e7-98b4-439cab1ba2e3.png)
This DOM element is not being deleted when alert is disappearing.
If I force delete this DOM element then it works again.

I tried to lower Angular Dependencies versions, then it works again.

Any solution?

**Comment by webcat12345** [comment]
Just tried every dependencies.
Error is coming from angular-cli version.

Exactly angular-cli 1.0.3 is Okay but 1.0.4 does not works.
Is this issue of angular-cli itself or related with sweetalert?

Any clarifications are welcome.

**Comment by seiyria** [comment]
This is not intended for any further use past rc.4. Check out some of the forks.

**Comment by webcat12345** [comment]
@seiyria , what do you mean?

**Comment by seiyria** [comment]
Do not use this if you're using ngModules.
