### ISSUE TITLE
please up your depencies 

### ISSUE THREAD

**Issue by MikhaelGerbet** [seiyria/ng2-sweetalert2#17]
the current version of  @angular/platform-browser is not @^2.0.0-rc.4 but @4.2.5  

https://www.npmjs.com/package/@angular/platform-browser

please up your dependencies

**Comment by seiyria** [comment]
This is not meant to be used past rc4. Import swal directly or use one of the forks that works more nicely (I recommend toverux)

**Comment by MikhaelGerbet** [comment]
+1
