### ISSUE TITLE
Update to use Angular Platform Browser RC4

### ISSUE THREAD

**Issue by SteveMunday** [seiyria/ng2-sweetalert2#2]
I've been trying for a while to get sweetalert2 to work in my Angular2 app and I think this library will solve it for me, but I cannot add it to my project because it fails to install on the latest build of angular2.  Any chance you could update this?

```
UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0-rc.4
...
npm WARN ng2-sweetalert2@0.0.3 requires a peer of @angular/platform-browser@2.0.0-rc.1 but none was installed.
```

**Comment by seiyria** [comment]
Feel free to send me a PR.
