### ISSUE TITLE
how to get it work without webpack

### ISSUE THREAD

**Issue by sinsunsan** [seiyria/ng2-sweetalert2#7]
Hello, 

You say 

> First, make sure you have a CSS loader set up for webpack, like so:
{
  test: /\.css/,
  loader: 'style!css'
},

but I am not using web pack but JSPM and system.js 

I have an error with the loading of sweetalert2.min.css.js that actually does  not exist. 
Do you have a clue on how to get it work ? 

```

GET http://localhost:8001/jspm_packages/npm/sweetalert2@5.3.8/dist/sweetalert2.min.css.js 404 (Not Found)
scheduleTask @ zone.js:1382
ZoneDelegate.scheduleTask @ zone.js:245
Zone.scheduleMacroTask @ zone.js:171
(anonymous) @ zone.js:1405
send @ VM80930:3
G @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:518
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2802
(anonymous) @ system.src.js:3380
(anonymous) @ system.src.js:3694
(anonymous) @ system.src.js:4086
(anonymous) @ system.src.js:4549
(anonymous) @ system.src.js:4819
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:232
Zone.run @ zone.js:114
(anonymous) @ zone.js:502
ZoneDelegate.invokeTask @ zone.js:265
Zone.runTask @ zone.js:154
drainMicroTaskQueue @ zone.js:401
ZoneTask.invoke @ zone.js:339
offres:47 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:8001/jspm_packages/npm/sweetalert2@5.3.8/dist/sweetalert2.min.css.js
	Error: XHR error (404 Not Found) loading http://localhost:8001/jspm_packages/npm/sweetalert2@5.3.8/dist/sweetalert2.min.css.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:8001/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:8001/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:8001/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:8001/node_modules/zone.js/dist/zone.js:335:33)

```

**Comment by seiyria** [comment]
This library was designed with webpack usage in mind. The reason I ask you to add a CSS loader is because I import the CSS in my JS so you don't have to. I'll accept a PR to make this more agnostic but I have no interest in doing it myself, as I only use webpack.

**Comment by sinsunsan** [comment]
Yes but which library ng2-sweetalert2 or sweealert2 it self ?

If it is yours, may be  I can comment a line to prevent this error to occur ? 
So that I can manually import sweet alert css with my way of doing this.

**Comment by seiyria** [comment]
I do this in ng2 sweetalert2

**Comment by sinsunsan** [comment]
I do not really see where ?

May be I should create a service with your code ? 
So that  get rid of your specific web pack settings
It is quite simple.... 


```js
var sweetAlert = require('sweetalert2');

export class SweetAlertService {
  constructor() {}

  swal(args = {}) {
    return sweetAlert(args);
  }

  prompt(options) {
    const baseOptions = {
      showCancelButton: true,
      confirmButtonText: 'Submit',
      input: 'text'
    };
    return sweetAlert(Object.assign({}, baseOptions, options));
  }

  confirm(options) {
    const baseOptions = {
      showCancelButton: true,
      confirmButtonText: 'Confirm',
      type: 'warning'
    };
    return sweetAlert(Object.assign(baseOptions, options));
  }

  alert(options) {
    const baseOptions = {
      confirmButtonText: 'OK',
      type: 'info'
    };
    return sweetAlert(Object.assign(baseOptions, options));
  }

  question(options) {
    return this.alert(Object.assign({ type: 'question' }, options));
  }

  success(options) {
    return this.alert(Object.assign({ type: 'success' }, options));
  }

  error(options) {
    return this.alert(Object.assign({ type: 'error' }, options));
  }

  warn(options) {
    return this.alert(Object.assign({ type: 'warn' }, options));
  }

  info(options) {
    return this.alert(Object.assign({ type: 'info' }, options));
  }
}
```

**Comment by seiyria** [comment]
Right here: https://github.com/seiyria/ng2-sweetalert2/blob/master/src/index.js#L3 is where I import the CSS.

**Comment by sinsunsan** [comment]
Ok thanks I will try to comment this line see if it works...

**Comment by sinsunsan** [comment]
Hello, 

I've succeeded using it by commenting the css line and importing the css manually
https://github.com/seiyria/ng2-sweetalert2/blob/master/src/index.js#L3

But it was a bit a pain using my fork with npm and jspm, so i think I will do my own ng2-sweetalert2-without-webpack something to have an easier configuration

But temporarly I use directly  the sweetalert2 in my service getting inspirations from what you do actually in the wrapper 
```
import swal from 'sweetalert2';
```

then swal ... without even defining it in the constructor. 

What is you wrapper for ? .... 
Not using wrapper will cause DI problems ?

**Comment by sinsunsan** [comment]
also I rewrited you doc on how to use in a component. 
Because I really not understand your syntax

```
import { SweetAlertService } from 'ng2-sweetalert2';

@Component({
  // if you import theservice globally in a @ngmodule 
  // this line is optional in the component
  providers: [SweetAlertService]
})
export class MyComponent {

 constructor(
    private sweetAlertService: SweetAlertService
 ) {}

 // Example method that use the service
 public onClick() {
    this.sweetAlertService.confirm('Are you sure ? ');
  }
```

**Comment by sinsunsan** [comment]
https://github.com/sinsunsan/ng2-sweetalert2

**Comment by seiyria** [comment]
no, it won't cause DI problems. I made this wrapper because having a simple wrapper that I can re-use across projects with common config holds value to me.

good to see you got it working.
